

const ENVLoad = import.meta.env


class Config {
    REACT_ENV;
    LOCAL_BACKEND_BASE_URL;
    VAPT_BACKEND_BASE_URL;
    DEMO_BACKEND_BASE_URL;
    SECUREND_BACKEND_BASE_URL;
    HUMAN_VERIFICATION;
    LOCAL_HUMAN_VERIFICATION;
    ENCRYPTION_KEY;

    // firebase 
    API_KEY;
    AUTH_DOMAIN;
    PROJECT_ID;
    STORAGE_BUCKET;
    APP_ID;
    MESSAGING_SENDER_ID;
    MEASUREMENT_ID;

    // file folder names
    SECUREND_FILE;
    DEMO_FILE;
    VAPT_FILE;
    LOCAL_FILE;

    constructor() {
        this.REACT_ENV = ENVLoad.VITE_REACT_ENV;
        this.LOCAL_BACKEND_BASE_URL = ENVLoad.VITE_LOCAL_BACKEND_BASE_URL;
        this.VAPT_BACKEND_BASE_URL = ENVLoad.VITE_VAPT_BACKEND_BASE_URL;
        this.DEMO_BACKEND_BASE_URL = ENVLoad.VITE_DEMO_BACKEND_BASE_URL;
        this.SECUREND_BACKEND_BASE_URL = ENVLoad.VITE_SECUREND_BACKEND_BASE_URL;
        this.LOCAL_HUMAN_VERIFICATION = ENVLoad.VITE_LOCAL_HUMAN_VERIFICATION;
        this.HUMAN_VERIFICATION = ENVLoad.VITE_HUMAN_VERIFICATION;
        this.ENCRYPTION_KEY = ENVLoad.VITE_ENCRYPTION_KEY;
        this.API_KEY = ENVLoad.VITE_API_KEY;
        this.AUTH_DOMAIN = ENVLoad.VITE_AUTH_DOMAIN;
        this.PROJECT_ID = ENVLoad.VITE_PROJECT_ID;
        this.STORAGE_BUCKET = ENVLoad.VITE_STORAGE_BUCKET;
        this.APP_ID = ENVLoad.VITE_APP_ID;
        this.MESSAGING_SENDER_ID = ENVLoad.VITE_MESSAGING_SENDER_ID;
        this.MEASUREMENT_ID = ENVLoad.VITE_MEASUREMENT_ID;
        this.SECUREND_FILE = ENVLoad.VITE_SECUREND_FILE;
        this.DEMO_FILE = ENVLoad.VITE_DEMO_FILE;
        this.VAPT_FILE = ENVLoad.VITE_VAPT_FILE;
        this.LOCAL_FILE = ENVLoad.VITE_LOCAL_FILE;
    }
};



export const config = new Config();






